     CREATE TABLE academy (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, academy_type INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     CREATE TABLE organisation (id INT AUTO_INCREMENT NOT NULL, academy_id INT DEFAULT NULL, owner VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, INDEX IDX_E6E132B46D55ACAB (academy_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;
     ALTER TABLE organisation ADD CONSTRAINT FK_E6E132B46D55ACAB FOREIGN KEY (academy_id) REFERENCES academy (id);

